var spentDict={},posBalanceName=[],posBalanceMoney=[],negBalanceName=[],negBalanceMoney=[],arrRotate=0,splitTable=[],splitIdx=0;
function addField(){var b=$("div[id^='p_row_']"),a;1>b.length?(a=$("#p_row").clone(!0),b=0):(b=parseInt(b.last().attr("id").replace("p_row_","")),a=$("#p_row_"+b).clone(!0));a.attr("id","p_row_"+(b+1));a.removeAttr("style");a.find("#remove_btn").removeAttr("disabled");a.find("#remove_btn").children().remove();a.find("#remove_btn").append("<img id='remove_img' SRC='"+IMG_DIR+"glyphicons-17-bin.png' class='remove_icon'>");0===b?a.insertAfter($("#p_row")):(a.insertAfter($("#p_row_"+b)),$("[id|='name']").last().val(""),
$("[id|='amount']").last().val(""))}function delRow(b){$(b).parent("div").remove()}
function sumAmount(){spentDict={};posBalanceName=[];posBalanceMoney=[];negBalanceName=[];negBalanceMoney=[];arrRotate=0;var b=!1;$("#div_error").empty();$("#div_error").append('<p class="lead"> <img src="'+IMG_DIR+'/glyphicons-505-alert.png" class="alert_icon"/> '+ERROR_IN_DATA+"</p>");$("#div_error").hide();$("#result").empty();$("#result").hide();$("div[id^='p_row_']").each(function(){var a=$(this).find("input");if("undefined"===typeof variable_here)var c=a[0].value;a=parseFloat(a[1].value);a=Math.round(100*
a)/100;""!==c||b?isNaN(a)&&!b||0>a?($("#div_error").append('<p class="error_color"> '+AMOUNT_GREATER_ZERO+"</p>"),$("#div_error").show("slow",function(){$("body").scrollTop($("#div_error").offset().top)}),b=!0):0<=a&&(spentDict[c]=a):($("#div_error").append('<p class="error_color"> '+NAMES_NOT_EMPTY+"</p>"),$("#div_error").show("slow",function(){$("body").scrollTop($("#div_error").offset().top)}),b=!0)});if(!b){var a=0,c;for(c in spentDict)a++;if(2>a)$("#div_error").append('<p class="error_color"> '+
LEAST_TWO_PERSON+"</p>"),$("#div_error").show("slow",function(){$("body").scrollTop($("#div_error").offset().top)});else{var f=0;for(c in spentDict)f+=spentDict[c];var a=Math.round(f/a*100)/100,d,e=0;for(c in spentDict){var g=spentDict[c]-a;0<=g?(posBalanceName.push(c),posBalanceMoney.push(g),d++):(negBalanceName.push(c),negBalanceMoney.push(-1*g),e++)}buildSplitTable();$("#result").empty();$("#result").append('<p class="lead"> <img src="'+IMG_DIR+'glyphicons-43-pie-chart.png"/> '+RESULT+"</p>");
$("#result").append('<p class="lead" class="amount_per_person_color"> '+TOTAL_COST+' <span class="error_color">$'+f.toFixed(2)+"</span></p>");$("#result").append('<p class="lead" class="amount_per_person_color"> '+AMOUNT_PER_PERSON+' <span class="error_color">$'+a.toFixed(2)+"</span></p>");$("#result").append('<p class="lead" class="split_ways_color"> '+TOTAL_SPLIT+' <span class="error_color">'+splitTable.length+"</span></p>");$("#result").append('<table cellspacing="0" class="table_result" id="table_result"></table>');
$("#result").append("<br><br>");$("#result").append('<div class="form-inline" id="res-buttons">');$("#res-buttons").append('<button type="button" id="changeWay"class="btn btn-success change_way_margin" onclick="showResult()"></button>');$("#res-buttons").append('<button type="button" id="back_btn" class="btn btn-info change_way_margin" onclick="backToMain()"><img src="'+IMG_DIR+'glyphicons-151-edit.png" class="result_icons_size">  '+BACK_TO_EDIT+"</button>");$("#res-buttons").append('<button type="button" id="clearButtom" class="btn btn-primary" onclick="reset()"><img src="'+
IMG_DIR+'glyphicons-366-restart.png" class="result_icons_size">  '+CLEAR+"</button><br>");$("#result").append("</div>");showResult()}}}
function showResult(){var b;1===splitTable.length?(b=TRY_ANOTHER_SPLIT,$("#changeWay").prop("disabled",!0)):b=TRY_ANOTHER_SPLIT+"("+(splitTable.length-splitIdx)+")";document.getElementById("changeWay").innerHTML='<img src="'+IMG_DIR+'glyphicons-84-random.png" class="result_icons_size">'+b;b=$("#table_result");b.empty();b.append("<tr><th>"+FROM+"</th><th>"+TO+"</th><th>"+AMOUNT_TO_PAY+"</th></tr>");splitIdx+1===splitTable.length?splitIdx=0:splitIdx++;for(var a=0;a<splitTable[splitIdx].length;a++)b.append("<tr><td>"+
splitTable[splitIdx][a].from+"</td><td>"+splitTable[splitIdx][a].to+"</td><td>$"+splitTable[splitIdx][a].amount.toFixed(2)+"</td></tr>");$("#result").show("slow",function(){$("body").scrollTop($("#result").offset().top)})}function buildSplitTable(){splitTable=[];splitIdx=0;totalCicles=negBalanceName.length*posBalanceName.length;for(var b=0;b<totalCicles;b++){var a=getNewSplit();if(duplicatedSplit(a))break;else splitTable.push(a)}}
function duplicatedSplit(b){if(0===splitTable.length)return!1;for(var a=0;a<splitTable.length;a++)if(splitEqual(b,splitTable[a]))return!0;return!1}function splitEqual(b,a){if(b.length!==a.length)return!1;for(var c=0;c<b.length;c++)if(!hasTheSplit(a,b[c]))return!1;for(c=0;c<a.length;c++)if(!hasTheSplit(b,a[c]))return!1;return!0}
function hasTheSplit(b,a){for(var c=0;c<b.length;c++)if(b[c].from===a.from&&b[c].to===a.to&&(b[c].amount===a.amount||Math.round(100*(b[c].amount-.01))/100===a.amount||Math.round(100*(b[c].amount+.01))/100===a.amount))return!0;return!1}
function getNewSplit(){arrRotate<negBalanceName.length?(rotateArr(negBalanceName),rotateArr(negBalanceMoney),1<posBalanceName.length&&arrRotate++):(rotateArr(posBalanceName),rotateArr(posBalanceMoney),arrRotate=0);for(var b=posBalanceMoney.slice(0),a=negBalanceMoney.slice(0),c=0,f=[],d=0;d<posBalanceName.length;d++)if(0!==b[d])for(var e=0;e<negBalanceName.length&&(0===a[e]||(b[d]>a[e]?(c=a[e],b[d]-=a[e],a[e]=0):(c=b[d],a[e]-=b[d],b[d]=0),c=Math.round(100*c)/100,tuple={from:negBalanceName[e],to:posBalanceName[d],
amount:c},f.push(tuple),0!==b[d]));e++);return f}function rotateArr(b){temp=b.shift();b.push(temp)}function changeWay(){isSplitPossible()||divideSpending()}function reset(){$("#result").hide("slow");$("div[id^='p_row_']").remove();addField();addField()}function backToMain(){$("#result").hide("slow");$("#header").show("slow",function(){$("body").scrollTop($("#header").offset().top)})};