var spentDict={},posBalanceName=[],posBalanceMoney=[],negBalanceName=[],negBalanceMoney=[],arrRotate=0,splitTable=[],splitIdx=0;
function addField(){var a=$("div[id^='p_row_']"),b;1>a.length?(b=$("#p_row").clone(!0),a=0):(a=parseInt(a.last().attr("id").replace("p_row_","")),b=$("#p_row_"+a).clone(!0));var c=a+1;b.attr("id","p_row_"+c);b.removeAttr("style");0===a?b.insertAfter($("#p_row")):(b.insertAfter($("#p_row_"+a)),$("[id|='name']").last().val(""),$("[id|='amount']").last().val(""));if(2<c){var f="#p_row_"+(c-2);$("#forms").show("slow",function(){$("body").scrollTop($(f).offset().top)})}b=PERSON+(a+1);spanVal="#p_row_"+
(a+1)+" span";$(spanVal).text(b)}function delRow(a){var b=a.parentElement.parentElement.parentElement.getAttribute("id"),b=parseInt(b.replace("p_row_",""));$("div[id^='p_row_']").each(function(){var a=this.getAttribute("id"),a=parseInt(a.replace("p_row_",""));if(a>b){var f="Person: "+(a-1);spanVal="#p_row_"+a+" span";$(spanVal).text(f);this.setAttribute("id","p_row_"+(a-1))}});$(a).parent().parent().parent("div").hide("slow");$(a).parent().parent().parent("div").remove()}
function sumAmount(){spentDict={};posBalanceName=[];posBalanceMoney=[];negBalanceName=[];negBalanceMoney=[];var a=!1;$("#logo").hide();$("#forms").hide();$("#footer").hide();$("#div_error").empty();$("#div_error").append('<p class="lead"> <img src="'+IMG_DIR+'/glyphicons-505-alert.png" class="alert_icon"/> '+ERROR_IN_DATA+"</p>");$("#div_error").hide();$("#result").empty();$("#result").hide();$("#op_btns").hide("slow");$("div[id^='p_row_']").each(function(){var b=$(this).find("input");if("undefined"===
typeof variable_here)var c=b[0].value;b=parseFloat(b[1].value);b=Math.round(100*b)/100;""!==c||a?isNaN(b)&&!a||0>b?($("#div_error").append('<p class="error_color"> '+AMOUNT_GREATER_ZERO+"</p>"),$("#div_error").show("slow",function(){$("body").scrollTop($("#div_error").offset().top)}),a=!0):0<=b&&(spentDict[c]=b):($("#div_error").append('<p class="error_color"> '+NAMES_NOT_EMPTY+"</p>"),$("#div_error").show("slow",function(){$("body").scrollTop($("#div_error").offset().top)}),a=!0)});if(a)appendBackBtn();
else{var b=0,c;for(c in spentDict)b++;if(2>b)$("#div_error").append('<p class="error_color"> '+LEAST_TWO_PERSON+"</p>"),$("#div_error").show("slow",function(){$("body").scrollTop($("#div_error").offset().top)}),appendBackBtn();else{var f=0;for(c in spentDict)f+=spentDict[c];var b=Math.round(f/b*100)/100,d,e=0;for(c in spentDict){var g=spentDict[c]-b;0<=g?(posBalanceName.push(c),posBalanceMoney.push(g),d++):(negBalanceName.push(c),negBalanceMoney.push(-1*g),e++)}buildSplitTable();$("#main_head").hide("slow");
$("#result").empty();$("#result").append('<p class="lead"> <img src="'+IMG_DIR+'glyphicons-43-pie-chart.png"/> '+RESULT+"</p>");$("#result").append('<span style="font-size:medium";> '+TOTAL_COST+' <span class="error_color">$'+f.toFixed(2)+"</span></p>");$("#result").append('<span style="font-size:medium"> '+AMOUNT_PER_PERSON+' <span class="error_color">$'+b.toFixed(2)+"</span></p>");$("#result").append('<span style="font-size:medium"> '+TOTAL_SPLIT+' <span class="error_color">'+splitTable.length+
"</span></p>");$("#result").append('<table cellspacing="0" class="table_result" id="table_result"></table>');$("#result").append("<br>");$("#result").append('<button type="button" id="changeWay" class="btn btn-success change_way_margin" onclick="showResult()"><img src="'+IMG_DIR+'glyphicons-84-random.png" class="result_icons_size">  '+TRY_ANOTHER_SPLIT+"</button>");$("#result").append("<br>");$("#result").append('<button type="button" id="back_btn" class="btn change_way_margin" onclick="backToMain()"><img src="'+
IMG_DIR+'glyphicons-211-left-arrow.png" class="result_icons_size">  '+BACK_TO_MAIN+"</button>");$("#result").append("<br>");$("#result").append('<button type="button" class="btn btn-primary" onclick="reset()"><img src="'+IMG_DIR+'glyphicons-366-restart.png" class="result_icons_size">  '+CLEAR+"</button><br>");showResult()}}}
function buildSplitTable(){splitTable=[];splitIdx=0;totalCicles=negBalanceName.length*posBalanceName.length;for(var a=0;a<totalCicles;a++){var b=getNewSplit();if(duplicatedSplit(b))break;else splitTable.push(b)}}
function showResult(){var a;1===splitTable.length?(a=TRY_ANOTHER_SPLIT,$("#changeWay").prop("disabled",!0)):a=TRY_ANOTHER_SPLIT+"("+(splitTable.length-splitIdx)+")";document.getElementById("changeWay").innerHTML='<img src="'+IMG_DIR+'glyphicons-84-random.png" class="result_icons_size">'+a;a=$("#table_result");a.empty();a.append("<tr><th>"+FROM+"</th><th>"+TO+"</th><th>"+AMOUNT_TO_PAY+"</th></tr>");splitIdx+1===splitTable.length?splitIdx=0:splitIdx++;for(var b=0;b<splitTable[splitIdx].length;b++)a.append("<tr><td>"+
splitTable[splitIdx][b].from+"</td><td>"+splitTable[splitIdx][b].to+"</td><td>$"+splitTable[splitIdx][b].amount.toFixed(2)+"</td></tr>");$("#result").show("slow",function(){$("body").scrollTop($("#result").offset().top)})}function duplicatedSplit(a){if(0===splitTable.length)return!1;for(var b=0;b<splitTable.length;b++)if(splitEqual(a,splitTable[b]))return!0;return!1}
function splitEqual(a,b){if(a.length!==b.length)return!1;for(var c=0;c<a.length;c++)if(!hasTheSplit(b,a[c]))return!1;for(c=0;c<b.length;c++)if(!hasTheSplit(a,b[c]))return!1;return!0}function hasTheSplit(a,b){for(var c=0;c<a.length;c++)if(a[c].from===b.from&&a[c].to===b.to&&(a[c].amount===b.amount||Math.round(100*(a[c].amount-.01))/100===b.amount||Math.round(100*(a[c].amount+.01))/100===b.amount))return!0;return!1}
function getNewSplit(){arrRotate<negBalanceName.length?(rotateArr(negBalanceName),rotateArr(negBalanceMoney),1<posBalanceName.length&&arrRotate++):(rotateArr(posBalanceName),rotateArr(posBalanceMoney),arrRotate=0);for(var a=posBalanceMoney.slice(0),b=negBalanceMoney.slice(0),c=0,f=[],d=0;d<posBalanceName.length;d++)if(0!==a[d])for(var e=0;e<negBalanceName.length&&(0===b[e]||(a[d]>b[e]?(c=b[e],a[d]-=b[e],b[e]=0):(c=a[d],b[e]-=a[d],a[d]=0),c=Math.round(100*c)/100,tuple={from:negBalanceName[e],to:posBalanceName[d],
amount:c},f.push(tuple),0!==a[d]));e++);return f}function rotateArr(a){temp=a.shift();a.push(temp)}function reset(){$("#result").hide("slow");$("div[id^='p_row_']").remove();addField();addField();$("#logo").show("slow");$("#main_head").show("slow");$("#forms").show("slow");$("#op_btns").show("slow");$("#footer").show("slow")}
function appendBackBtn(){var a='<button type="button" id="back_btn" class="btn" onclick="backToMain()"><img src="'+IMG_DIR+'glyphicons-211-left-arrow.png" class="result_icons_size">  '+BACK_TO_MAIN+"</button>";$("#div_error").append(a)}function backToMain(){$("#div_error").hide("slow");$("#result").hide("slow");$("#about").hide("slow");$("#logo").show("slow");$("#main_head").show("slow");$("#forms").show("slow");$("#op_btns").show("slow");$("#footer").show("slow")}
function showAbout(){$("#div_error").hide("slow");$("#result").hide("slow");$("#forms").hide("slow");$("#op_btns").hide("slow");$("#footer").hide("slow");$("#about").show()};